### ISSUE TITLE
Doesn't properly work with multiple users inside container?

### ISSUE THREAD

**Issue by slonopotamus** [boxboat/fixuid#21] opened 2019-08-20 10:16 UTC
There are two users in docker container
1. dockeralice:dockeralice (1000:1000)
2. dockerbob:dockerbob (1001:1001)

We specify in docker file:
```
USER dockeralice:dockeralice
ENTRYPOINT ["fixuid"]
```

We add `/etc/fixuid/config.yml` to container:

```
user: dockeralice
group: dockeralice
```

Now, when alice:alice (1000:1000) from host runs this image with `-u 1000:1000` then everything is fine.

However, if bob:bob (1001:1001) from host runs this image with `-u 1001:0001`, he will become a dockerbob inside container instead of dockeralice because his uid=1001 matched dockerbob's uid=1001.

Is there any way for bob to become a dockeralice inside container with such setup?

So, the problem is that in such case when host user UID accidentally clashes with UID inside container, both `USER` from dockerfile and `user` from `/etc/fixuid/config.yml` are totally ignored.

**Comment by polarathene** [comment] 2019-11-16 04:32
I haven't used `fixuid` yet to verify/confirm, but as a workaround, couldn't you use the container users with IDs that are far less likely to clash?

Your description also implies that `fixuid` may not be working in your setup? Since the `-u 1001:1001` option should have the same effect without `fixuid`. Did you look at ownership of files? Ones from `dockeralice` should have been adjusted to `dockerbob` ownership if I understand correctly what `fixuid` does. 

If you want to run the container with the `dockeralice` ownership transferred to bob's machine/login, then you use `-u 1000:1000`. 

Perhaps you misunderstand the purpose of the container?:

> *Go binary to change Docker container user/group and file permissions at runtime*

Your example wasn't clear, but it seems like you're trying to have multiple users in the container that match users that run the container? If that's not the case, what is the actual issue you're trying to resolve? What are the other users for?

**Comment by slonopotamus** [comment] 2019-11-19 06:27
My description implies that there is an [explicit logic](https://github.com/boxboat/fixuid/blob/master/fixuid.go#L142) that fully ignores `/etc/fixuid/config.yml` if `-u <whatever>` acidentally clashed with some user listed in `/etc/passwd` inside fixuid'ed container, no more no less.

**Comment by polarathene** [comment] 2019-11-19 16:31
@slonopotamus the linked code you're referencing doesn't seem to have a problem at achieving what `fixuid` is meant to do?

If bob uses `-u 1000:1000` on the container, then the linked line you gave will be a match, nothing happens. If bob used `-u 1001:1001`, the match to the yml user fails, and it applies chown(all UID/GID ownerships for dockeralice end up becoming dockerbob instead as it should).

I wouldn't say that's fully ignoring the yml config?

---

https://github.com/boxboat/fixuid/blob/8d82f123bc0340a56b9acdae7318cc73b9671c49/fixuid.go#L172

The earlier condition will also run this should the given UID/GID not exist within the container, which replaces the target user UID/GID with the given runtime values and performs a chown again. This ensures that the new user you've asked the container to run as, has a $HOME, avoiding issues. If a user already existed, this shouldn't be an issue, so it's not performed.

---

In your case, your wanting to specifically target a user/group and enforce that they their UID/GID replaced with the runtime values. That's only useful if you have other processes running as users that are not the runtime user, but expect that users processes to have the ownership of the runtime UID/GID. With the code as is, that would mean there are two users and groups both with 1001, which would be invalid, you'd need to replace dockerbob UID/GID with something else.

That's not really a good approach to be catering for is it?

> So, the problem is that in such case when host user UID accidentally clashes with UID inside container, both `USER` from dockerfile and `user` from `/etc/fixuid/config.yml` are totally ignored.

`--user` / `-u` overrides `USER` does it not? `containerUser` in the go code refers to the `user` from the yml config. If it's the same as what you provide, then there's no need to do anything, so it's technically ignored(like with alice in your example).

`fixuid` is doing it's job in that it syncs the given runtime UID/GID values to the `USER` that Dockerfile would have declared(which the yaml config is meant to reflect as per the README).

**Comment by slonopotamus** [comment] 2019-11-19 16:46
I possibly should explain why I am passing `-u` at all. Container that we're speaking of, writes files to bind-mounted dir from host system. Bob wants to be able to access files after container has shut down. So he *needs* to run it with `-u` matching Bob's UID on the host system. So, what he actually does is `-u $(id -u)`. Bob just doesn't have an option to pass any different value.

What Bob needs (and what this issue is all about) is to pass his host UID into container but have container contents adjusted in such a way that he becomes dockeralice. And fixuid *does* that unless unlucky Bob has UID (that he is unable to change) that matches with some *other* user inside container. In such situation, there's no way for Bob to become dockeralice with Bob's UID.

**Comment by caleblloyd** [comment] 2019-11-19 17:22
I think the situation that you are describing is not the [existingUser == containerUser](https://github.com/boxboat/fixuid/blob/master/fixuid.go#L142) conditional, it is [this conditional](https://github.com/boxboat/fixuid/blob/master/fixuid.go#L144-L145)

Let's break it down by the example, running with `-u 1001:0001`

```
/etc/fixuid/config.yml:
user: dockeralice   // (UID 1000)
group: dockeralice   // (GID 1000)
```

```go
        containerUser := rootConfig.GetString("user")
        // dockeralice
        
	existingUser, _ := findUser(runtimeUID)
        // dockerbob

	if existingUser == "" {
                // false
		logInfo("updating user '" + containerUser + "' to UID '" + runtimeUID + "'")
		needChown = true
		oldUID = containerUID
		newUID = runtimeUID
	} else {
		oldUID = ""
		newUID = ""
		if existingUser == containerUser {
                       // false
			logInfo("runtime UID '" + runtimeUID + "' already matches container user '" + containerUser + "' UID")
		} else {
                        // true
			logInfo("runtime UID '" + runtimeUID + "' matches existing user '" + existingUser + "'; not changing UID")
			needChown = true
		}
	}
```

So the User Name and Group Name will still be `dockerbob:dockerbob`, but files/dirs owned by `dockeralice:dockeralice` will still be chown'd to `1001:1001` since `needChown = true`

`fixuid` will chown the files, but it will not change usernames or home directories in this case

take for example running with `-u 0:0`.  `fixuid` will chown files matching the user/group in `config.yaml` to `0:0`, but it will not change the name or home directory of `root`

**Comment by slonopotamus** [comment] 2019-11-19 17:39
> I think the situation that you are describing is not the existingUser == containerUser conditional, it is this conditional

You're right, sorry.

**Comment by polarathene** [comment] 2019-11-20 01:47
Which is what I was trying to say? I guess I didn't explain it as well?

> *If bob uses `-u 1000:1000` on the container, then the linked line you gave will be a match, nothing happens. If bob used `-u 1001:1001`, the match to the yml user fails, and it applies chown(all UID/GID ownerships for dockeralice end up becoming dockerbob instead as it should).*

dockeralice doesn't have the UID/GID replaced in this case with the runtime UID/GID provided. You don't use dockeralice $HOME, and processes that run under dockeralice will continue to use `1000:1000` instead of the initial `1001:1001` conversion that `fixuid` applied. You end up using the dockerbob user for the main process and their $HOME in the container.

> What Bob needs (and what this issue is all about) is to pass his host UID into container but have container contents adjusted in such a way that he becomes dockeralice. And fixuid does that unless unlucky Bob has UID (that he is unable to change) that matches with some other user inside container. In such situation, there's no way for Bob to become dockeralice with Bob's UID.

That is still true, and probably out of scope of `fixuid` I assume. You can have the dockeralice ownership transferred to dockerbob, but to assign the same UID to two users would be a conflict afaik, so the dockeralice user if running any processes(eg via s6/supervisord or other configs), dockeralice will continue to operate with `1000:1000` and write files as such.

If that's an issue, you should assign UIDs to the containers users that aren't going to conflict with `--user` values. But keep in mind, only one user in the container can adopt the assigned UID.

---

All sorted now? Can close the issue?

**Comment by slonopotamus** [comment] 2019-11-20 05:38
> you should assign UIDs to the containers users that aren't going to conflict with --user values

That's what I did to workaround the issue, but I don't count this as a proper solution.

> to assign the same UID to two users would be a conflict afaik

True, so their UIDs would need to be swapped, for example.

> probably out of scope of fixuid I assume

Then close the issue, okay.

**Comment by polarathene** [comment] 2019-11-20 11:20
> That's what I did to workaround the issue, but I don't count this as a proper solution.

Are you actually running multiple processes in the container under different users, and choosing to give them UIDs from 1000 and up? Just change the base UID for these internal users to be higher, especially if this is an internal/private image. 

You're making a problem that really shouldn't be one(especially since `fixuid` is only intended for development purposes).

If all you wanted was for changing ownership of files at container init, and whatever the Dockerfile `USER` is running as, then you're fine, you shouldn't have any problems.

> True, so their UIDs would need to be swapped, for example.

That doesn't sound like a good idea, especially if this other user(s) in the container write files to persistent storage as well. The correct approach is to avoid conflict in the first place.

> Then close the issue, okay.

I can't do that, only you or a member of BoxBoat can. Not a bug, raise a new issue as a feature request, close this one and link to it for reference. 

## [FEATURE]: Force update UID/GID

When the runtime UID/GID provided exists in the container, it will avoid `updateEtcPasswd()` or `updateEtcGroup()` due to conflict. I want to force the runtime UID/GID to be applied to the target container UID/GID in the yml config, swapping the value and ownership of the conflicting UID/GID with the targets.

[show use case here that conveys why this is needed for development, such as processes managed by s6/supervisord that don't run as the runtime provided UID/GID that overrides the `USER` in Dockerfile]

---

Submit something like the example above, but be a bit more clear on your actual use-case which you're still vague about for some reason.

**Closed as completed** 2019-11-20 11:30 UTC
